config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users

  resources :contacts do
    collection do
    end
    member do
      post 'call', :action => 'call'
    end
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('name ASC') }

  validates :user_id, :presence => true
  validates :name, :presence => true,  :length => { :maximum => 30}
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :allow_blank => true
  validates :email, :length => { :maximum => 50}

  validates_format_of :phone, :with => /\A[-+]?[0-9]+\z/, :allow_blank => true
  validates :phone, :length => { :maximum => 15}

  #validates :last_called, :length => { :maximum => 15}


  # call the contact, update last_called
  def call
    self.last_called = DateTime.now
  end

  # call the contact, update last_called
  def call!
    self.call
    self.save
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy, :call]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /contacts/1/call
  # POST /contacts/1/call.json
  def call
    puts "!!!!!!!!!!!!!!!!"

    respond_to do |format|
      @contact.call
      if @contact.save
        format.html { redirect_to contacts_path, notice: 'Contact was successfully called.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find_by_id(params[:id])

      raise ActionController::RoutingError.new('Not Found') unless @contact

      if not @contact
        render(:file => File.join(Rails.root, 'public/404.html'), :status => 404, :layout => false)
      elsif @contact.user != current_user
        render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone, :email)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.slim
= simple_form_for @contact, :html => {:class => 'form-horizontal'  } do |f|
  = f.error_notification


  .form-group
    label.col-sm-2.control-label
      | Name
    .col-sm-10
      = f.input_field :name
  .form-group
    label.col-sm-2.control-label
      | Phone number
    .col-sm-10
      = f.input_field :phone
      = f.error :phone

  .form-group
    label.col-sm-2.control-label
      | Email
    .col-sm-10
      = f.input_field :email
      = f.error :email



  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button :submit, :class => 'btn-primary'

app/views/contacts/edit.html.slim
h1 Editing contact

== render 'form'

= link_to 'Show', @contact
'|
= link_to 'Back', contacts_path

app/views/contacts/index.html.slim
h1 Listing contacts

= link_to 'New Contact', new_contact_path, :class => "btn btn-large btn-primary"

br
br

table#contacts.table.table-bordered
  thead
    tr
      th Name
      th Phone
      th Email
      th Last Called
      th

  tbody
    - @contacts.each do |contact|
      tr
        td = contact.name
        td = contact.phone
        td = contact.email
        td
          = contact.last_called.to_formatted_s(:long) if  contact.last_called
          = link_to call_contact_path(contact), :method => :post, :class => "call"
            button.btn.btn-success.btn-xs
              | Call

        td
          = link_to edit_contact_path(contact)
            button.btn.btn-default.btn-xs
              span.glyphicon.glyphicon-pencil
          = link_to contact, data: {:confirm => 'Are you sure?'}, :method => :delete
            button.btn.btn-default.btn-xs
              span.glyphicon.glyphicon-trash

br

app/views/contacts/new.html.slim
h1 New contact

== render 'form'

= link_to 'Cancel', contacts_path, :class => "btn"

app/views/contacts/show.html.slim
p#notice = notice

p
  strong Name:
  = @contact.name
p
  strong Phone:
  = @contact.phone
p
  strong Email:
  = @contact.email

= link_to 'Edit', edit_contact_path(@contact)
'|
= link_to 'Back', contacts_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  li
    = link_to 'Contacts', contacts_path
  li
    = link_to 'Edit account', edit_user_registration_path
  li
    = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  li
    = link_to 'Sign in', new_user_session_path
  li
    = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Callem'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Callem'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>